packages:
  - apps/*
  - libs/*

autoInstallPeers: true
allowBuilds:
  nx: true
  unrs-resolver: true
  "@nestjs/core": false
  '@parcel/watcher': true
  less: true
  esbuild: true
  lightningcss: true
  '@prisma/engines': true
  '@scarf/scarf': false
  prisma: true
