/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppSaleRouteImport } from './routes/_app/sale'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppStaffRouteImport } from './routes/_app/staff'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AppInventoryIndexRouteImport } from './routes/_app/inventory/index'
import { Route as AppInvoiceIndexRouteImport } from './routes/_app/invoice/index'
import { Route as AppInvoiceIdRouteImport } from './routes/_app/invoice/$id'
import { Route as AppOwnerIndexRouteImport } from './routes/_app/owner/index'
import { Route as AppOwnerIdRouteImport } from './routes/_app/owner/$id'
import { Route as AppOwnerAddRouteImport } from './routes/_app/owner/add'
import { Route as AppPatientIndexRouteImport } from './routes/_app/patient/index'
import { Route as AppPatientIdRouteImport } from './routes/_app/patient/$id'
import { Route as AppPatientAddRouteImport } from './routes/_app/patient/add'
import { Route as AppProductIndexRouteImport } from './routes/_app/product/index'
import { Route as AppRecordIndexRouteImport } from './routes/_app/record/index'
import { Route as AppTreatmentIndexRouteImport } from './routes/_app/treatment/index'
import { Route as AppVisitIndexRouteImport } from './routes/_app/visit/index'
import { Route as AppVisitIdRouteImport } from './routes/_app/visit/$id'
import { Route as AppVisitRegisterRouteImport } from './routes/_app/visit/register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSaleRoute = AppSaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoiceIndexRoute = AppInvoiceIndexRouteImport.update({
  id: '/invoice/',
  path: '/invoice/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoiceIdRoute = AppInvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOwnerIndexRoute = AppOwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => AppRoute,
} as any)
const AppOwnerIdRoute = AppOwnerIdRouteImport.update({
  id: '/owner/$id',
  path: '/owner/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOwnerAddRoute = AppOwnerAddRouteImport.update({
  id: '/owner/add',
  path: '/owner/add',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientIndexRoute = AppPatientIndexRouteImport.update({
  id: '/patient/',
  path: '/patient/',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientIdRoute = AppPatientIdRouteImport.update({
  id: '/patient/$id',
  path: '/patient/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientAddRoute = AppPatientAddRouteImport.update({
  id: '/patient/add',
  path: '/patient/add',
  getParentRoute: () => AppRoute,
} as any)
const AppProductIndexRoute = AppProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordIndexRoute = AppRecordIndexRouteImport.update({
  id: '/record/',
  path: '/record/',
  getParentRoute: () => AppRoute,
} as any)
const AppTreatmentIndexRoute = AppTreatmentIndexRouteImport.update({
  id: '/treatment/',
  path: '/treatment/',
  getParentRoute: () => AppRoute,
} as any)
const AppVisitIndexRoute = AppVisitIndexRouteImport.update({
  id: '/visit/',
  path: '/visit/',
  getParentRoute: () => AppRoute,
} as any)
const AppVisitIdRoute = AppVisitIdRouteImport.update({
  id: '/visit/$id',
  path: '/visit/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppVisitRegisterRoute = AppVisitRegisterRouteImport.update({
  id: '/visit/register',
  path: '/visit/register',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/sale': typeof AppSaleRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invoice/$id': typeof AppInvoiceIdRoute
  '/owner/$id': typeof AppOwnerIdRoute
  '/owner/add': typeof AppOwnerAddRoute
  '/patient/$id': typeof AppPatientIdRoute
  '/patient/add': typeof AppPatientAddRoute
  '/visit/$id': typeof AppVisitIdRoute
  '/visit/register': typeof AppVisitRegisterRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/invoice/': typeof AppInvoiceIndexRoute
  '/owner/': typeof AppOwnerIndexRoute
  '/patient/': typeof AppPatientIndexRoute
  '/product/': typeof AppProductIndexRoute
  '/record/': typeof AppRecordIndexRoute
  '/treatment/': typeof AppTreatmentIndexRoute
  '/visit/': typeof AppVisitIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/sale': typeof AppSaleRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invoice/$id': typeof AppInvoiceIdRoute
  '/owner/$id': typeof AppOwnerIdRoute
  '/owner/add': typeof AppOwnerAddRoute
  '/patient/$id': typeof AppPatientIdRoute
  '/patient/add': typeof AppPatientAddRoute
  '/visit/$id': typeof AppVisitIdRoute
  '/visit/register': typeof AppVisitRegisterRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/invoice': typeof AppInvoiceIndexRoute
  '/owner': typeof AppOwnerIndexRoute
  '/patient': typeof AppPatientIndexRoute
  '/product': typeof AppProductIndexRoute
  '/record': typeof AppRecordIndexRoute
  '/treatment': typeof AppTreatmentIndexRoute
  '/visit': typeof AppVisitIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/sale': typeof AppSaleRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/staff': typeof AppStaffRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_app/invoice/$id': typeof AppInvoiceIdRoute
  '/_app/owner/$id': typeof AppOwnerIdRoute
  '/_app/owner/add': typeof AppOwnerAddRoute
  '/_app/patient/$id': typeof AppPatientIdRoute
  '/_app/patient/add': typeof AppPatientAddRoute
  '/_app/visit/$id': typeof AppVisitIdRoute
  '/_app/visit/register': typeof AppVisitRegisterRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/invoice/': typeof AppInvoiceIndexRoute
  '/_app/owner/': typeof AppOwnerIndexRoute
  '/_app/patient/': typeof AppPatientIndexRoute
  '/_app/product/': typeof AppProductIndexRoute
  '/_app/record/': typeof AppRecordIndexRoute
  '/_app/treatment/': typeof AppTreatmentIndexRoute
  '/_app/visit/': typeof AppVisitIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/sale'
    | '/settings'
    | '/staff'
    | '/auth/callback'
    | '/invoice/$id'
    | '/owner/$id'
    | '/owner/add'
    | '/patient/$id'
    | '/patient/add'
    | '/visit/$id'
    | '/visit/register'
    | '/inventory/'
    | '/invoice/'
    | '/owner/'
    | '/patient/'
    | '/product/'
    | '/record/'
    | '/treatment/'
    | '/visit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/sale'
    | '/settings'
    | '/staff'
    | '/auth/callback'
    | '/invoice/$id'
    | '/owner/$id'
    | '/owner/add'
    | '/patient/$id'
    | '/patient/add'
    | '/visit/$id'
    | '/visit/register'
    | '/inventory'
    | '/invoice'
    | '/owner'
    | '/patient'
    | '/product'
    | '/record'
    | '/treatment'
    | '/visit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/dashboard'
    | '/_app/sale'
    | '/_app/settings'
    | '/_app/staff'
    | '/auth/callback'
    | '/_app/invoice/$id'
    | '/_app/owner/$id'
    | '/_app/owner/add'
    | '/_app/patient/$id'
    | '/_app/patient/add'
    | '/_app/visit/$id'
    | '/_app/visit/register'
    | '/_app/inventory/'
    | '/_app/invoice/'
    | '/_app/owner/'
    | '/_app/patient/'
    | '/_app/product/'
    | '/_app/record/'
    | '/_app/treatment/'
    | '/_app/visit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sale': {
      id: '/_app/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof AppSaleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoice/': {
      id: '/_app/invoice/'
      path: '/invoice'
      fullPath: '/invoice/'
      preLoaderRoute: typeof AppInvoiceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoice/$id': {
      id: '/_app/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/invoice/$id'
      preLoaderRoute: typeof AppInvoiceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/owner/': {
      id: '/_app/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof AppOwnerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/owner/$id': {
      id: '/_app/owner/$id'
      path: '/owner/$id'
      fullPath: '/owner/$id'
      preLoaderRoute: typeof AppOwnerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/owner/add': {
      id: '/_app/owner/add'
      path: '/owner/add'
      fullPath: '/owner/add'
      preLoaderRoute: typeof AppOwnerAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patient/': {
      id: '/_app/patient/'
      path: '/patient'
      fullPath: '/patient/'
      preLoaderRoute: typeof AppPatientIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patient/$id': {
      id: '/_app/patient/$id'
      path: '/patient/$id'
      fullPath: '/patient/$id'
      preLoaderRoute: typeof AppPatientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patient/add': {
      id: '/_app/patient/add'
      path: '/patient/add'
      fullPath: '/patient/add'
      preLoaderRoute: typeof AppPatientAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/product/': {
      id: '/_app/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof AppProductIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/record/': {
      id: '/_app/record/'
      path: '/record'
      fullPath: '/record/'
      preLoaderRoute: typeof AppRecordIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/treatment/': {
      id: '/_app/treatment/'
      path: '/treatment'
      fullPath: '/treatment/'
      preLoaderRoute: typeof AppTreatmentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visit/': {
      id: '/_app/visit/'
      path: '/visit'
      fullPath: '/visit/'
      preLoaderRoute: typeof AppVisitIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visit/$id': {
      id: '/_app/visit/$id'
      path: '/visit/$id'
      fullPath: '/visit/$id'
      preLoaderRoute: typeof AppVisitIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visit/register': {
      id: '/_app/visit/register'
      path: '/visit/register'
      fullPath: '/visit/register'
      preLoaderRoute: typeof AppVisitRegisterRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppSaleRoute: typeof AppSaleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppInvoiceIdRoute: typeof AppInvoiceIdRoute
  AppOwnerIdRoute: typeof AppOwnerIdRoute
  AppOwnerAddRoute: typeof AppOwnerAddRoute
  AppPatientIdRoute: typeof AppPatientIdRoute
  AppPatientAddRoute: typeof AppPatientAddRoute
  AppVisitIdRoute: typeof AppVisitIdRoute
  AppVisitRegisterRoute: typeof AppVisitRegisterRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppInvoiceIndexRoute: typeof AppInvoiceIndexRoute
  AppOwnerIndexRoute: typeof AppOwnerIndexRoute
  AppPatientIndexRoute: typeof AppPatientIndexRoute
  AppProductIndexRoute: typeof AppProductIndexRoute
  AppRecordIndexRoute: typeof AppRecordIndexRoute
  AppTreatmentIndexRoute: typeof AppTreatmentIndexRoute
  AppVisitIndexRoute: typeof AppVisitIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppSaleRoute: AppSaleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
  AppInvoiceIdRoute: AppInvoiceIdRoute,
  AppOwnerIdRoute: AppOwnerIdRoute,
  AppOwnerAddRoute: AppOwnerAddRoute,
  AppPatientIdRoute: AppPatientIdRoute,
  AppPatientAddRoute: AppPatientAddRoute,
  AppVisitIdRoute: AppVisitIdRoute,
  AppVisitRegisterRoute: AppVisitRegisterRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppInvoiceIndexRoute: AppInvoiceIndexRoute,
  AppOwnerIndexRoute: AppOwnerIndexRoute,
  AppPatientIndexRoute: AppPatientIndexRoute,
  AppProductIndexRoute: AppProductIndexRoute,
  AppRecordIndexRoute: AppRecordIndexRoute,
  AppTreatmentIndexRoute: AppTreatmentIndexRoute,
  AppVisitIndexRoute: AppVisitIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
